### ISSUE TITLE
Value too long for column

### ISSUE THREAD

**Issue by chuy08** [sentric/hannibal#24]
Hello,

I am attempting to use Hannibal to help me monitor my hbase cluster, 8 nodes.  Our cluster is mainly used for opentsdb.

Hannibal was easy enough to compile and get working.  As I tail the log file however I am seeing it complaining about the names of my regions being to long to insert into it's database.

[info] application - creating new metric for 91c9b9cb89499fb89d53bbfbe03f63ab : storefileSizeMB
[ERROR] [09/04/2013 10:49:33.669] [application-akka.actor.default-dispatcher-40] [akka://application/user/updateMetricsActor] Value too long for column "TARGET_DESC VARCHAR(255) DEFAULT '-unkown-' SELECTIVITY 25": "'tsdb,\x00\x00\x16Q\x12\x8C\x10\x00\x00\x01\x00\x19x\x00\x00\x02\x00\x00\x02\x00\x00\x03\x00\x19t\x00\x00\x04\x00\x00\x04\x00\x0... (261)"; SQL statement:
INSERT INTO       metric(target, name, last_value, last_update, target_desc)     VALUES       (?, ?, 0.0, 0, ?) [22001-158]
org.h2.jdbc.JdbcSQLException: Value too long for column "TARGET_DESC VARCHAR(255) DEFAULT '-unkown-' SELECTIVITY 25": "'tsdb,\x00\x00\x16Q\x12\x8C\x10\x00\x00\x01\x00\x19x\x00\x00\x02\x00\x00\x02\x00\x00\x03\x00\x19t\x00\x00\x04\x00\x00\x04\x00\x0... (261)"; SQL statement:
INSERT INTO       metric(target, name, last_value, last_update, target_desc)     VALUES       (?, ?, 0.0, 0, ?) [22001-158]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
    at org.h2.message.DbException.get(DbException.java:169)
    at org.h2.table.Column.validateConvertUpdateSequence(Column.java:319)
    at org.h2.table.Table.validateConvertUpdateSequence(Table.java:679)
    at org.h2.command.dml.Insert.insertRows(Insert.java:120)
    at org.h2.command.dml.Insert.update(Insert.java:84)
    at org.h2.command.CommandContainer.update(CommandContainer.java:71)
    at org.h2.command.Command.executeUpdate(Command.java:212)
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:143)
    at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:129)
    at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
    at anorm.Sql$class.execute1(Anorm.scala:447)
    at anorm.SimpleSql.execute1(Anorm.scala:359)
    at anorm.Sql$class.executeInsert(Anorm.scala:454)
    at anorm.SimpleSql.executeInsert(Anorm.scala:359)
    at models.MetricDef$$anonfun$find$1.apply(Metric.scala:41)
    at models.MetricDef$$anonfun$find$1.apply(Metric.scala:36)
    at play.api.db.DBApi$class.withConnection(DB.scala:79)
    at play.api.db.BoneCPApi.withConnection(DB.scala:273)
    at play.api.db.DB$$anonfun$withConnection$3.apply(DB.scala:158)
    at play.api.db.DB$$anonfun$withConnection$3.apply(DB.scala:158)
    at scala.Option.map(Option.scala:133)
    at play.api.db.DB$.withConnection(DB.scala:158)
    at models.MetricDef$.find(Metric.scala:36)
    at models.MetricDef$.findRegionMetricDef(Metric.scala:33)
    at models.MetricDef$.STOREFILE_SIZE_MB(Metric.scala:22)
    at actors.UpdateMetricsActor$$anonfun$receive$1$$anonfun$apply$1$$anonfun$apply$mcI$sp$1.apply(UpdateMetricsActor.scala:30)
    at actors.UpdateMetricsActor$$anonfun$receive$1$$anonfun$apply$1$$anonfun$apply$mcI$sp$1.apply(UpdateMetricsActor.scala:29)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at actors.UpdateMetricsActor$$anonfun$receive$1$$anonfun$apply$1.apply$mcI$sp(UpdateMetricsActor.scala:29)
    at actors.UpdateMetricsActor.updateMetrics(UpdateMetricsActor.scala:87)
    at actors.UpdateMetricsActor$$anonfun$receive$1.apply(UpdateMetricsActor.scala:26)
    at actors.UpdateMetricsActor$$anonfun$receive$1.apply(UpdateMetricsActor.scala:23)
    at akka.actor.Actor$class.apply(Actor.scala:318)
    at actors.UpdateMetricsActor.apply(UpdateMetricsActor.scala:22)
    at akka.actor.ActorCell.invoke(ActorCell.scala:626)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:197)
    at akka.dispatch.Mailbox.run(Mailbox.scala:179)
    at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:516)
    at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
    at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
    at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1479)
    at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

Thanks,

Jesus Orosco

**Comment by meniku** [comment]
Thanks for the report, issue should be fixed on the 'next' branch

**Comment by chuy08** [comment]
Wow thanks for the quick response!!!  That worked perfectly.

+1
