### ISSUE TITLE
Installation instructions in README.markdown links to old version

### ISSUE THREAD

**Issue by victorjerlin** [sentric/hannibal#27]
The database schema doesn't permit region names longer than 255 bytes.

Received the following exception:

[ERROR] [02/20/2014 02:57:44.125] [application-akka.actor.default-dispatcher-1] [akka://application/user/updateMetricsActor] Value too long for column "TARGET_DESC VARCHAR(255) DEFAULT '-unkown-' SELECTIVITY 33": "able,region-name-that-is-very-loong... (358)"; SQL statement:
INSERT INTO       metric(target, name, last_value, last_update, target_desc)     VALUES       (?, ?, 0.0, 0, ?) [22001-158]
org.h2.jdbc.JdbcSQLException: Value too long for column "TARGET_DESC VARCHAR(255) DEFAULT '-unkown-' SELECTIVITY 33": "table,region-name-that-is-very-loong... (358)"; SQL statement:
INSERT INTO       metric(target, name, last_value, last_update, target_desc)     VALUES       (?, ?, 0.0, 0, ?) [22001-158]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
        at org.h2.message.DbException.get(DbException.java:169)
        at org.h2.table.Column.validateConvertUpdateSequence(Column.java:319)
        at org.h2.table.Table.validateConvertUpdateSequence(Table.java:679)
        at org.h2.command.dml.Insert.insertRows(Insert.java:120)
        at org.h2.command.dml.Insert.update(Insert.java:84)
        at org.h2.command.CommandContainer.update(CommandContainer.java:71)
        at org.h2.command.Command.executeUpdate(Command.java:212)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:143)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:129)
        at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:203)
        at anorm.Sql$class.execute1(Anorm.scala:447)
        at anorm.SimpleSql.execute1(Anorm.scala:359)
        at anorm.Sql$class.executeInsert(Anorm.scala:454)
        at anorm.SimpleSql.executeInsert(Anorm.scala:359)
        at models.MetricDef$$anonfun$find$1.apply(Metric.scala:41)
        at models.MetricDef$$anonfun$find$1.apply(Metric.scala:36)
        at play.api.db.DBApi$class.withConnection(DB.scala:79)
        at play.api.db.BoneCPApi.withConnection(DB.scala:273)
        at play.api.db.DB$$anonfun$withConnection$3.apply(DB.scala:158)
        at play.api.db.DB$$anonfun$withConnection$3.apply(DB.scala:158)
        at scala.Option.map(Option.scala:133)
        at play.api.db.DB$.withConnection(DB.scala:158)
        at models.MetricDef$.find(Metric.scala:36)
        at models.MetricDef$.findRegionMetricDef(Metric.scala:33)
        at models.MetricDef$.STOREFILE_SIZE_MB(Metric.scala:22)
        at actors.UpdateMetricsActor$$anonfun$receive$1$$anonfun$apply$1$$anonfun$apply$mcI$sp$1.apply(UpdateMetricsActor.scala:30)
        at actors.UpdateMetricsActor$$anonfun$receive$1$$anonfun$apply$1$$anonfun$apply$mcI$sp$1.apply(UpdateMetricsActor.scala:29)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
        at scala.collection.immutable.List.foreach(List.scala:45)
        at actors.UpdateMetricsActor$$anonfun$receive$1$$anonfun$apply$1.apply$mcI$sp(UpdateMetricsActor.scala:29)
        at actors.UpdateMetricsActor.updateMetrics(UpdateMetricsActor.scala:87)
        at actors.UpdateMetricsActor$$anonfun$receive$1.apply(UpdateMetricsActor.scala:26)
        at actors.UpdateMetricsActor$$anonfun$receive$1.apply(UpdateMetricsActor.scala:23)
        at akka.actor.Actor$class.apply(Actor.scala:318)
        at actors.UpdateMetricsActor.apply(UpdateMetricsActor.scala:22)
        at akka.actor.ActorCell.invoke(ActorCell.scala:626)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:197)
        at akka.dispatch.Mailbox.run(Mailbox.scala:179)
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:516)
        at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
        at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
        at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1479)
        at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

**Comment by meniku** [comment]
Are you using the latest Hannibal version? Since Hannbail 0.9.1 the limit should be 1000 characters, not 255. 

However, we should consider to remove the target_desc column altogether, as it's only required to hod the full region name to display it in the frontend. Internally Hannibal hashes the region name and uses the 'target'-column.
For our display purpses it would be much better if we instead just add another table that maps the hash to the region name. This would allow us to store arbitrary long region names and also reduce the size of the database significantly.

**Comment by victorjerlin** [comment]
Hi,

Thanks for your answer, you are entirely right.  I'm using 0.9.0 and not the latest version,  I just assumed I was since I installed it 10 days ago.

The link to the release page in README.markdown links to https://github.com/sentric/hannibal/releases/v.0.9.0 which is the reason why I missed that there is a 0.10.0.

Maybe should consider changing it to https://github.com/sentric/hannibal/releases/latest ?

/Victor

/Victor

**Comment by meniku** [comment]
Thanks for the tip, I changed the link in the README. 

I'll leave the Ticket open, because the schema really should be changed.
