### ISSUE TITLE
Hannibal with HBase 1.0.0 version

### ISSUE THREAD

**Issue by pankaj2461** [sentric/hannibal#39]
Hi Guys,

I am trying to build Hannibal with HBase 1.0.0 version. Build is successful but while starting Hannibal below error is thrown in the console,

Play server process ID is 4559
[info] play - database [default] connected at jdbc:h2:data/metrics.h2
[error] application - Could not instanciate any api wrapper, Hannibal will now exit

Any help would be much appreciated.

**Comment by amithkanand** [comment]
I built `Hannibal` with `HBase 1.1.3` and got the same error.

```
(Starting server. Type Ctrl+D to exit logs, the server will remain in background)

Play server process ID is 45244
[info] play - database [default] connected at jdbc:h2:data/metrics.h2
[error] application - Could not instanciate any api wrapper, Hannibal will now exit
```

**Comment by amithkanand** [comment]
I was able to get past the error by adding  `1.1.3` to list of `apiVersions` in [`Global.scala`](https://github.com/sentric/hannibal/blob/next/app/Global.scala#L11-L15).

**Comment by meniku** [comment]
Interesting, did you add an implementation for that api?

**Comment by amithkanand** [comment]
I did add an implementation and it is working for me now. If anyone is interested they can clone `hbase113` branch from my [github](https://github.com/amithkanand/hannibal/tree/hbase113). I am currently working on implementing changes to make it work on a `secure(kerberos)` cluster.

**Comment by clairvoyant-rohit** [comment]
Is this working . After adding keytabs and other configs for hannibal user , i am still facing issue starting hannibal on secured (keroborized) hbase . 

Can someone let me know the exact configuration that needs to be added to the hbase-site.xml ? 

Error : 
[error] o.a.h.h.i.AbstractRpcClient - SASL authentication failed. The most likely cause is missing or invalid credentials. Consider 'kinit'.
javax.security.sasl.SaslException: GSS initiate failed
	at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211) ~[na:1.8.0_131]
	at org.apache.hadoop.hbase.security.HBaseSaslRpcClient.saslConnect(HBaseSaslRpcClient.java:179) ~[org.apache.hbase.hbase-client-1.1.3.jar:1.1.3]
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupSaslConnection(RpcClientImpl.java:612) [org.apache.hbase.hbase-client-1.1.3.jar:1.1.3]
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.access$600(RpcClientImpl.java:157) [org.apache.hbase.hbase-client-1.1.3.jar:1.1.3]
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection$2.run(RpcClientImpl.java:738) ~[org.apache.hbase.hbase-client-1.1.3.jar:1.1.3]
Caused by: org.ietf.jgss.GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
	at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147) ~[na:1.8.0_131]
	at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122) ~[na:1.8.0_131]
	at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187) ~[na:1.8.0_131]
	at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224) ~[na:1.8.0_131]
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212) ~[na:1.8.0_131]

**Comment by amithkanand** [comment]
I have modified `hannibal` to enable `Kerberos` support and `HBase 1.1.3`. Please try using my [fork](https://github.com/amithkanand/hannibal/tree/play24).

**Comment by clairvoyant-rohit** [comment]
I have tried that and it still gives me exception on kinit failure . Can you share the hbase-site.xml with required parameters ?

- Created hannibal user and did kinit with this users principal. 
- Tried kinit with Principal for HBase Master 

Nothing worked for me yet . Is there something i am missing here. I have followed all steps as per documents shared on different links .

**Comment by clairvoyant-rohit** [comment]
Can someone help me with this ? Really need this get going as we want to start monitoring the HBASE on production cluster .

**Comment by amithkanand** [comment]
@clairvoyant-rohit I can help you with this. Do you want to reach out to me via hangouts? I can be reached at `anandkamith@gmail.com`

**Comment by clairvoyant-rohit** [comment]
Sent Invite .

- Rohit Pathak

**Comment by husenzhang** [comment]
does hannibal 0.98 support HBase 2.2.6?

**Comment by meniku** [comment]
Hi Husen,

Sorr, Hannibal hasn't been updated for years,  so my guess is no. Maybe you
can find some more up to date fork.

Cheers,
Nils

Husen Zhang ***@***.***> schrieb am Di., 7. Dez. 2021, 01:41:
