### ISSUE TITLE
Exception occurred while waiting for cluster table to show up

### ISSUE THREAD

**Issue by ranlo** [sentric/hannibal#5]
- Started hannibal
- pointed to localhost:9000
- after ~4 minutes the following  exception showed up in the logs, and the browser showed 'done with errors' and a blank page.
- immediately after that i tried opening localhost:9000 from chrome and it opened fine

[info] application - start updating CompactionMetrics... (Fri Dec 14 17:55:12 IS
T 2012)
[ERROR] [12/14/2012 17:55:17.863] [application-akka.actor.default-dispatcher-11]
 [akka://application/user/updateMetricsActor] Promise timed out after 5000 : MIL
LISECONDS
java.util.concurrent.TimeoutException: Promise timed out after 5000 : MILLISECON
DS
        at play.api.libs.concurrent.STMPromise$$anonfun$await$1.apply(Promise.sc
ala:158)
        at play.api.libs.concurrent.STMPromise$$anonfun$await$1.apply(Promise.sc
ala:154)
        at scala.concurrent.stm.ccstm.InTxnImpl.runBlock(InTxnImpl.scala:538)
        at scala.concurrent.stm.ccstm.InTxnImpl.topLevelAttempt(InTxnImpl.scala:
494)
        at scala.concurrent.stm.ccstm.InTxnImpl.topLevelAtomicImpl(InTxnImpl.sca
la:365)
        at scala.concurrent.stm.ccstm.InTxnImpl.atomic(InTxnImpl.scala:244)
        at scala.concurrent.stm.ccstm.CCSTMExecutor.apply(CCSTMExecutor.scala:24
)
        at play.api.libs.concurrent.STMPromise.await(Promise.scala:154)
        at play.api.libs.concurrent.Promise$class.await(Promise.scala:55)
        at play.api.libs.concurrent.STMPromise.await(Promise.scala:110)
        at play.api.libs.concurrent.Promise$class.value(Promise.scala:53)
        at play.api.libs.concurrent.STMPromise.value(Promise.scala:110)
        at models.Compaction$$anonfun$all$1.apply(Compaction.scala:64)
        at models.Compaction$$anonfun$all$1.apply(Compaction.scala:61)
        at utils.HBaseConnection$$anonfun$eachServer$1$$anonfun$apply$2.apply(HB
aseConnection.scala:37)
        at utils.HBaseConnection$$anonfun$eachServer$1$$anonfun$apply$2.apply(HB
aseConnection.scala:36)
        at scala.collection.Iterator$class.foreach(Iterator.scala:660)
        at scala.collection.JavaConversions$JIteratorWrapper.foreach(JavaConvers
ions.scala:573)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:73)
        at scala.collection.JavaConversions$JCollectionWrapper.foreach(JavaConve
rsions.scala:592)
        at utils.HBaseConnection$$anonfun$eachServer$1.apply(HBaseConnection.sca
la:36)
        at utils.HBaseConnection$$anonfun$eachServer$1.apply(HBaseConnection.sca
la:33)
        at utils.HBaseConnection$class.withHBaseAdmin(HBaseConnection.scala:47)
        at models.Compaction$.withHBaseAdmin(Compaction.scala:17)
        at utils.HBaseConnection$class.eachServer(HBaseConnection.scala:33)
        at models.Compaction$.eachServer(Compaction.scala:17)
        at models.Compaction$.all(Compaction.scala:60)
        at actors.UpdateMetricsActor$$anonfun$receive$1$$anonfun$apply$2.apply$m
cI$sp(UpdateMetricsActor.scala:44)
        at actors.UpdateMetricsActor.updateMetrics(UpdateMetricsActor.scala:75)
        at actors.UpdateMetricsActor$$anonfun$receive$1.apply(UpdateMetricsActor
.scala:42)
        at actors.UpdateMetricsActor$$anonfun$receive$1.apply(UpdateMetricsActor
.scala:21)
        at akka.actor.Actor$class.apply(Actor.scala:318)
        at actors.UpdateMetricsActor.apply(UpdateMetricsActor.scala:20)
        at akka.actor.ActorCell.invoke(ActorCell.scala:626)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:197)
        at akka.dispatch.Mailbox.run(Mailbox.scala:179)
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(
AbstractDispatcher.scala:516)
        at akka.jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:259)
        at akka.jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
        at akka.jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1479)
        at akka.jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

@gissues:{"order":20,"status":"backlog"}

**Comment by meniku** [comment]
Thank you for the bug-report, I guess that it takes too long to fetch the logfiles from your cluster.

It may help if you increase the timeout for fetching the compaction log-files by increasing the value of 'compactions.logfile-fetch-timeout-in-seconds' in conf/application.conf. 

I will try to add a more helpful error message and to increase the default timeout.

**Comment by meniku** [comment]
I changed the default timeout to 30 seconds and hope that solves your issues. But I have no idea about your browser showing "'done with errors' and a blank page". Can you write back whether that still happens?

**Comment by ranlo** [comment]
increased the timeout. the exception still appears. btw - it could be that the browser errors are unrelated. do you want me to open a new, separate issue?

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E)
Timestamp: Fri, 14 Dec 2012 17:34:57 UTC

Message: Object doesn't support this property or method
Line: 3078
Char: 3
Code: 0
URI: http://localhost:9000/assets/javascripts/d3.v2.js

Message: Object doesn't support this property or method
Line: 396
Char: 2
Code: 0
URI: http://localhost:9000/assets/javascripts/rickshaw.js

**Comment by alexandre-normand** [comment]
It seems from the last comments that the timeout on fetching the region server logs is gone but I'm still commenting here to give some additional background from my experience with this. 

The 5 seconds default timeout was very aggressive for us since our log max file size is 200 MB. Getting 200 MB under 5 seconds from the host I was running hannibal on was just not feasible. The real problem though is that such huge files will always take a very long time to download. It's also a problem with the memory consomption since the content of the entire log file is kept in memory before parsing. Streaming the content would really help with that but there was a lower-hanging fruit which is just being a bit smarter in fetching logs.  

Pull request https://github.com/sentric/hannibal/pull/7 is my solution to this problem. The log file is retrieved with a range to start from where the last fetch ended. The initial fetch going back 1024 KB (configurable) prior to the current end of the log. With this code, I've been able to remove my heap size setting of 2048 MB and keep the default value without OutOfMemory errors. Also, the 5 seconds timeout was sufficient for me since in most cases, a fetch would be at most 1024 KB (unless logs produce more than 1 MB per 5 minutes).

**Comment by meniku** [comment]
That's true and I am very happy with your solution - maybe we can also reduce the timeout back to 5 seconds.

**Comment by alexandre-normand** [comment]
I'm actually having second thoughts and I'm not entirely sure if my testing on Friday was done using 5 or 30 seconds. In any case, each log fetch felt like less than 5 seconds. 

I will check again tomorrow though but I think it would actually make more sense to have the timeout as lenient as it can be to be able to fetch logs for all region servers inside a refresh interval (which I made more agressive in the pull request https://github.com/sentric/hannibal/issues/7).

**Comment by alexandre-normand** [comment]
The fetching of logs is definitely faster now. I'm running this against a 20 nodes cluster and the compaction metrics update takes 8700 ms, well under 5 seconds for each region server.

**Comment by meniku** [comment]
Ranlo It seams that you are using Internet Explorer 8, which doesn't support SVG. The graphs from Hannibal are rendered with SVG. Could you try another browser?
